### ISSUE TITLE
Safely kill the node

### ISSUE THREAD

**Issue by tngan** [dji-sdk/Guidance-SDK-ROS#19]
How can I exit and rerun the node safely ? When I terminate the guidanceNode (ctrl-c) after running `rosrun guidance guidanceNode` successfully for a while, the error message shows up when I rerun the guidanceNode.

```
llibusb_get_device_list ret = 9 !!!
Waiting for board ready ...
Error: e_timeout at 247, /.........../guidanceNode.cpp
```
and the line 247 is the code for guidance initialization.

**Comment by tngan** [comment]
The program exits before `stop_transfer` and `release_transfer`. It could be exited by pressing the `q` button.

**Comment by curantil** [comment]
I think this is because sleep(1) on line 363 is used. On Windows sleep is in seconds, but on Linux it is in microseconds. It thus has no time to wait for the ack package.
