### ISSUE TITLE
 e_disparity_not_allowed at 291

### ISSUE THREAD

**Issue by Aswath93** [dji-sdk/Guidance-SDK-ROS#23]
Hey guys,

When I try `rosrun guidance guidanceNode` after connecting to the guidance bundle using USB , I get  the following error

`aswath@aswath-HP-ENVY-m7-Notebook:~$ rosrun guidance guidanceNode 
llibusb_get_device_list ret = 6 !!! 
Waiting for board ready...
Sensor online status: 1 1 1 1 1 
cu	cv	focal	baseline
161.182	119.527	225.564	0.149806
160.24	127.999	240.597	0.149597
159.087	129.332	246.825	0.149493
162.332	121.654	229.558	0.149414
152.014	117.394	234.919	0.149491
Error: e_disparity_not_allowed at 291,/home/aswath/ros/src/Guidance-SDK-ROS/src/GuidanceNode.cpp
`
nothing is being published on any of the topics. I just want to read the messages being published on the topics.

I am not able to caliberate the cameras on my own too as there is nothing being published on the `/guidance/right/image_raw` or `/guidance/right/image_raw` topics

Kindly help me rectify this issue.

Regards,
Aswath

**Comment by tangketan** [comment]
Error says you are not allowed to get disparity or depth. This happens when you are at **standard mode** and enabled obstacle sensing function.

**Comment by Aswath93** [comment]
thank you for replying.how do i disable standard mode from my terminal?

**Comment by Aswath93** [comment]
I had to go to windows to use the DJI app to change the mode to DIY and calibrated the sensors again. now it works in ubuntu . Is there someway to change the modes in ubuntu?

**Comment by tangketan** [comment]
Sorry but there is no way to do so currently in ubuntu.

**Comment by Aswath93** [comment]
thanks
