### ISSUE TITLE
Guidance Motion high drift

### ISSUE THREAD

**Issue by AlexisTM** [dji-sdk/Guidance-SDK-ROS#26]
Hi,

The motion (position) output of the guidance system (after calibration & setting the position of the sensors) is heavily drifting. What should I do to reduce the drift ? Why does it drift that much ?

**Comment by tangketan** [comment]
Did You use Guidance along with a DJI flight controller? 
Also, the precision is heavily influenced by the environment. Good lighting, rich texture and regular motion should give You reasonably good result.

**Comment by AlexisTM** [comment]
Dear, 
It was with ROS, but we have an A3, not a M100. Therefore, it is no DJI Flight Controller connected to it.

**Comment by tangketan** [comment]
Guidance has a poor onboard IMU. Try to connect Guidance with a DJI flight controller. A3 should also work.

**Comment by AlexisTM** [comment]
Thanks, I will try

2016-12-02 14:26 GMT+01:00 tangketan <notifications@github.com>:

**Comment by AlexisTM** [comment]
Will there be any chance to be able to send the quaternion to the Guidance System from a ROS node?

**Comment by dan748** [comment]
Hi @AlexisTM, were you able to solve the high drift problem, i am also facing this problem and can't seem to be able to fix it. 

Also did you figure anything out about being able to send quaternion to the guidance from ROS?

**Comment by AlexisTM** [comment]
No, it did not work.
We switched to the PX4Flow for vision odometry and stereo camera for
obstacle avoidance.

**Comment by AlexisTM** [comment]
Outdated.

**Comment by AlexisTM** [comment]
Outdated.
