### ISSUE TITLE
ros::NodeHandle::SpinOnce almost never called

### ISSUE THREAD

**Issue by AlexisTM** [dji-sdk/Guidance-SDK-ROS#29]
Hi,

The spinOnce function has to be called in order to call callbacks, or use the logs like `ROS_DEBUG("Some log");`. 

https://github.com/dji-sdk/Guidance-SDK-ROS/blob/master/src/GuidanceNode.cpp#L354

```c++
	while (ros::ok())
	{
		if (key > 0){
			[...]
			ros::spinOnce();
		}
	}
```

should be 

```c++
	while (ros::ok())
	{
		if (key > 0){
			[...]
		}
                ros::spinOnce();
	}
```

**Comment by lanyusea** [comment]
agree

**Comment by tangketan** [comment]
@AlexisTM Thanks. Bug fixed.
