### ISSUE TITLE
Right and Left images same

### ISSUE THREAD

**Issue by madratman** [dji-sdk/Guidance-SDK-ROS#3]
Please fix typo https://github.com/dji-sdk/Guidance-SDK-ROS/blob/master/src/GuidanceNode.cpp#L85
Took me quite some time to find this, and had been thinking it was some fault in my code.
`g_greyscale_image_left.copyTo(right_8.image);`
Left and right images are same

**Comment by tangketan** [comment]
Sorry for the mistake and thank you very much for pointing it out. This typo is now fixed.
