### ISSUE TITLE
Obstacle Avoidance?

### ISSUE THREAD

**Issue by szx0112** [dji-sdk/Guidance-SDK-ROS#38]
Just new to guidance ROS. Does the ROS package contains the build-in function of obstacle avoidance ?
I want to have it work on my own DIY drone.

Any comment is appreciate.

Thanks,

**Comment by semihyildirim** [comment]
There is a demo for obstacle avoidance on Guidance-SDK repo on github.com/dji-sdk. But I can not run it. Could you manage it?
