### ISSUE TITLE
e_disparity_not_allowed 

### ISSUE THREAD

**Issue by madratman** [dji-sdk/Guidance-SDK-ROS#7]
I've been getting this error for a couple of days now. Unable to debug.
Running via guidance sdk work fine, but I get this via the ros wrapper:
```
$ rosrun guidance guidanceNode
llibusb_get_device_list ret = 10 !!! 
Waiting for board ready...
Sensor online status: 1 1 1 1 1 
cu	cv	focal	baseline
155.784	114.505	195.721	0.148784
177.886	101.42	303.124	0.150098
172.085	87.0126	336.415	0.148536
167.922	101.562	306.625	0.148215
164.785	89.875	319.882	0.148857
Error: e_disparity_not_allowed at 272,/home/ratneshmadaan/projects/dji_ros_ws_orig/src/Guidance-SDK-ROS/src/GuidanceNode.cpp
```

The calib params are also quite different from what I got earlier https://github.com/dji-sdk/Guidance-SDK-ROS/blob/master/calibration_files/camera_params_left.yaml 
The difference is this time I calibrated it with the drone, and earlier I was calibrating without the drone. 

Edit: Yeah, I just recalibrated without the drone using the `DIY` mode and it works. Calibrating with the drone is leading to the above error.

**Comment by dji-dev** [comment]
Dear sir,
What was the work type you selected? Please select DIY type.
[cid:image002.jpg@01D1341D.77A2F800]

Thank you for your support of DJI.

Best Regards,
DJI SDK Team



发件人: Ratnesh Madaan [mailto:notifications@github.com]
发送时间: 2015年12月11日 3:01
收件人: dji-sdk/Guidance-SDK-ROS
主题: [Guidance-SDK-ROS] e_disparity_not_allowed (#7)


I've been getting this error for a couple of days now. Unable to debug.
Running via guidance sdk work fine, but I get this via the ros wrapper:

$ rosrun guidance guidanceNode

llibusb_get_device_list ret = 10 !!!

Waiting for board ready...

Sensor online status: 1 1 1 1 1

cu  cv  focal   baseline

155.784 114.505 195.721 0.148784

177.886 101.42  303.124 0.150098

172.085 87.0126 336.415 0.148536

167.922 101.562 306.625 0.148215

164.785 89.875  319.882 0.148857

Error: e_disparity_not_allowed at 272,/home/ratneshmadaan/projects/cmu_airlab/dji/dji_ros_ws_orig/src/Guidance-SDK-ROS/src/GuidanceNode.cpp

—
Reply to this email directly or view it on GitHub<https://github.com/dji-sdk/Guidance-SDK-ROS/issues/7>.




-----CONFIDENTIAL：

This email and any attachments thereto may contain private, confidential, and privileged material for the sole use of the intended recipient. Any review, copying, or distribution of this email (or any attachments thereto) by others is strictly prohibited. If you are not the intended recipient, please contact the sender immediately and permanently delete the original and any copies of this email and any attachments thereto.
-----机密：

此电子邮件及附件所包含内容具有机密性，且仅限于接收人使用。未经允许，禁止第三人阅读、复制或传播该电子邮件中的任何信息。如果您不属于以上电子邮件的目标接收者，请您立即通知发送人并删除原电子邮件及其相关的附件。
DJI, Inc. <http://www.dji.com>

**Comment by peteflorence** [comment]
Also getting an `e_disparity_not_allowed` error

Current status is that I have not calibrated.  Would we expect this error to exist prior to calibration?

Due to this error, I am unable to proceed with calibration in ROS as documented here [https://github.com/dji-sdk/Guidance-SDK-ROS#using-ros-tools-for-calibration-and-stereo-processing](url)

Because I get the error while trying to run the guidanceNodeCalibration node

```
peteflo@peteflo-i7gtx:~/fla-gtsc/fla_root/fsw$ rosrun guidance guidanceNodeCalibration  
llibusb_get_device_list ret = 20 !!! 
Waiting for board ready...
Sensor online status: 1 1 1 1 1 
cu	cv	focal	baseline
155.608	119.036	246.705	0.149657
162.174	126.546	238.85	0.149923
160.165	118.695	249.628	0.149559
159.782	127.96	248.269	0.149608
156.673	125.981	237.76	0.149548
Error: e_disparity_not_allowed at 372,/home/peteflo/fla-gtsc/fla_root/fsw/src/Guidance-SDK-ROS/src/GuidanceNodeCalibration.cpp
```

I will attempt to do the calibration in Windows?  Any other ideas would be appreciated

@madratman Seems like you might be one to know?  Would appreciate your "Guidance"!  :)

**Comment by peteflorence** [comment]
Edit to above:

I no longer have this error after going through Guidance Assistant on Windows.  It seems running Guidance Assistant, enabling the USB API, choosing which depth images to push over USB (up to 2) , etc, is required
